apiVersion: v3
name: eloq-operator
description: A Helm chart for deploying Monograph Operator to Kubernetes.
version: 2.0.6
appVersion: "3.0.0"
keywords:
  - database
  - newsql
  - mariadb
  - mysql
  - redis
  - bigtable
  - cassandra
  - dynamodb
  - operator

dependencies:
  - name: cert-manager
    alias: certmanager
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
    version: ">=1.13.1"

source:
  - https://github.com/monographdb/eloq-operator

maintainers:
  - name: MonographDB Inc
    url: https://www.eloqdata.com/
