# Default values for eloq-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

timezone: UTC
appendReleaseSuffix: false

## controller manager
controllerManager:
  serviceAccount:
    name: "eloq-operator-controller-manager-sa"
    annotations: { }
  image:
    repository: monographdb/eloq-operator
    tag: v1.0.4
  imagePullPolicy: IfNotPresent
  ## In case the above image is pulled from a registry that requires
  ## authentication, a secret containining credentials can be added
  ## imagePullSecrets:
  ##   - secret_with_credentials_to_custom_registry
  imagePullSecrets: { }
  resources:
    requests:
      cpu: 1
      memory: "1Gi"
    limits:
      cpu: 1
      memory: "1Gi"
  healthPort: 18080
  metricPort: 18081
  ## Set `watchNamespaces` to watch the specific namespaces, otherwise the controller by default watches all
  ## MonographDBCluster in all namespaces.
  ## e.g.
  ## watchNamespaces: "N1, N2, N3"
  watchNamespaces: ""
  enabledLeaderElect: false
  ## This ServiceMonitor is to serve the metrics of the monograph operator
  ## controller manager.
  serviceMonitor:
    release: kube-prometheus-stack
  env: [ ]

## Setting keepCrds to false will delete CRDs after helm uninstall the release
keepCrds: true

cert-manager:
  # -- Install cert-manger. Set to false to use an existing cert-manager
  enabled: false
