apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eloq-operator.fullname" . }}-proxy-cluster-role
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    {{- include "eloq-operator.commonLabels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eloq-operator.fullname" . }}-proxy-cluster-rolebinding
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    {{- include "eloq-operator.commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "eloq-operator.fullname" . }}-proxy-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.controllerManager.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
