apiVersion: v2
name: eloq-monitoring
description: A Helm chart for deploying monitoring infra of EloqDB to Kubernetes.
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - Prometheus
  - Grafana
  - Loki
  - Promtail

dependencies:
  - name: kube-prometheus-stack
    version: "~56.13.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: loki-distributed
    version: "~0.78.3"
    repository: "https://grafana.github.io/helm-charts"
  - name: promtail
    version: "~6.15.5"
    repository: "https://grafana.github.io/helm-charts"
  - name: mimir-distributed
    version: "~5.2.1"
    repository: "https://grafana.github.io/helm-charts"


maintainers:
  - name: MonographDB Inc
    url: https://www.eloqdata.com/
