# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monograph-operator.name" . }}-controller-manager-metrics-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: metrics
    release: {{ .Values.controllerManager.serviceMonitor.release }}
    {{- include "monograph-operator.commonLabels" . | nindent 4 }}
    {{- include "monograph-operator.controlPlaneLabels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
      - targetLabel: instance
        replacement: "monograph-controller"
        action: replace
  selector:
    matchLabels:
      {{- include "monograph-operator.selectorLabels" . | nindent 6 }}
      {{- include "monograph-operator.controlPlaneLabels" . | nindent 6 }}
