{{- if .Values.loki-distributed.enabled }}
loki:
  structuredConfig:
    ingester:
      # Disable chunk transfer which is not possible with statefulsets
      # and unnecessary for boltdb-shipper
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 1536000
      max_chunk_age: 1h
    compactor:
      shared_store: s3
      working_directory: /tmp/loki/compactor
      retention_enabled: true
      compaction_interval: 10m
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    limits_config:
      max_query_lookback: 336h # 14 days
      retention_period: 336h   # 14 days
  schemaConfig:
    configs:
      - from: "2020-09-07"
        store: tsdb         # boltdb-shipper
        object_store: aws  # filesystem
        schema: v12 # v11
        index:
          prefix: loki_index_
          period: 24h
  storageConfig:
    tsdb_shipper:
      shared_store: s3  #filesystem
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 1h  # 168h
      # index_gateway_client:
      #   server_address: dns:///index-gateway.<namespace>.svc.cluster.local:9095
    aws:
      s3: s3://{{ .Values.global.aws.region }}
      bucketnames: {{ .Values.loki-distributed.bucketnames }}
      region: {{.Values.global.aws.region}}
      s3forcepathstyle: false
      insecure: false
      http_config:
        idle_conn_timeout: 30s
        response_header_timeout: 0s
        insecure_skip_verify: false
serviceAccount:
  create: false
  name: {{ .Values.global.serviceAccount.name }}
  automountServiceAccountToken: true
ingester:
  kind: StatefulSet
  replicas: 1
  persistence:
    enabled: true
    claims:
      - name: data
        size: {{ .Values.loki-distributed.ingester.persistence.dataStorageSpec.size }}
        storageClass: {{ .Value.loki-distributed.ingester.persistence.dataStorageSpec.storageClass }}
      - name: wal
        size: {{ .Values.loki-distributed.ingester.persistence.walStorageSpec.size }}
        storageClass: {{ .Values.loki-distributed.ingester.persistence.walStorageSpec.storageClass }}
  resources:
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi


querier:
  max_concurrent: 16
compactor:
  enabled: true
{{- end}}
