{{- if .Values.promtail.enable }}
config:
  clients:
    - url: http://loki-distributed-gateway/loki/api/v1/push
  snippets:
    extraRelabelConfigs:
      - source_labels:
          - __meta_kubernetes_pod_label_eloqdata_com_cluster
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: eloqdata_cluster
      - source_labels:
          - __meta_kubernetes_pod_label_eloqdata_com_srv
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: eloqdata_srv
    pipelineStages:
      - match:
          selector: '{eloqdata_srv="tx"}'
          stages:
            - regex:
                expression: '\[time\s+(?P<time>\S+)\]\s+\[level\s+(?P<level>\w+)\]\s+\[thread\s+(\d+)\]\s+\[\s*(.*?):(\d+)\]\s+(.*)'
            - labels:
                level:
            - timestamp:
                source: time
                format: '2006-01-02T15:04:05.999999'
{{- end}}
